services:
  web:
    container_name: codelabs-api-v2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - codelabs-network

  mongodb:
    container_name: codelabs-mongodb
    image: mongo:7.0-alpine
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-changeMe}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - codelabs-network

volumes:
  mongodb_data:

networks:
  codelabs-network:
    driver: bridge
