services:
  web:
    container_name: codelabs-api-v2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - codelabs-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  codelabs-network:
    driver: bridge
